# Sponsor the Payments Management System development
# Your support helps maintain and improve this open-source payment processing platform

github: [ayushmaanbhav]
custom: ['https://upi.link/payment?pa=8544130924@pthdfc&pn=Ayush%20Jain&cu=INR&am=&tn=Sponsor%20Payments%20Management%20System']

# Sponsor: Ayush Jain
# UPI ID: 8544130924@pthdfc
# Currency: INR (Indian Rupee)
#
# Your sponsorship helps with:
# - Continuous development and maintenance
# - Adding new payment gateway integrations
# - Security updates and bug fixes
# - Documentation improvements
# - Community support
