name: Bug Report
description: Report a bug to help us improve the Payments Management System
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us identify and fix the issue.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the Payments Management System are you running?
      placeholder: "e.g., 1.1.4-SNAPSHOT"
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which module is affected by this bug?
      multiple: true
      options:
        - ayushmaanbhav-payment
        - ayushmaanbhav-ledger
        - ayushmaanbhav-gateway-provider
        - ayushmaanbhav-gateway-provider-setu
        - ayushmaanbhav-event-processor
        - ayushmaanbhav-request-idempotency
        - ayushmaanbhav-commons
        - ayushmaanbhav-commons-spring
        - ayushmaanbhav-database
        - ayushmaanbhav-client
        - Other / Not sure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a payment order with...
        2. Call the endpoint...
        3. Observe the error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Development (local)
        - Staging
        - Production
        - Docker
        - Kubernetes
        - Other
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: What version of Java are you using?
      placeholder: "e.g., OpenJDK 11.0.12"
    validations:
      required: true

  - type: input
    id: database
    attributes:
      label: Database Version
      description: What version of MySQL are you using?
      placeholder: "e.g., MySQL 8.0.28"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, configuration, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched the existing issues to make sure this bug has not been reported before
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I am willing to submit a PR to fix this bug (optional)
