name: Feature Request
description: Suggest a new feature or enhancement for the Payments Management System
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Payment Gateway Integration
        - New API Endpoint
        - Ledger Enhancement
        - Performance Improvement
        - Security Enhancement
        - Documentation
        - Developer Experience
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module(s) would this feature affect?
      multiple: true
      options:
        - ayushmaanbhav-payment
        - ayushmaanbhav-ledger
        - ayushmaanbhav-gateway-provider
        - ayushmaanbhav-gateway-provider-common
        - ayushmaanbhav-event-processor
        - ayushmaanbhav-request-idempotency
        - ayushmaanbhav-commons
        - ayushmaanbhav-database
        - New module required
        - Not sure
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear description of what the problem is. Ex: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "A clear description of what you want to happen..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "List any alternative approaches..."

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this involves new API endpoints, please provide a proposed design
      placeholder: |
        ```
        POST /payment/new-endpoint
        Request:
        {
          "field1": "value1"
        }
        Response:
        {
          "success": true,
          "data": { ... }
        }
        ```
      render: markdown

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes to existing APIs?
      options:
        - "No"
        - "Yes - Minor (backwards compatible with deprecation)"
        - "Yes - Major (breaking change)"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Blocking my use case
        - Critical - Cannot use the system without this
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: "Explain how you would use this feature..."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to this feature?
      options:
        - label: I am willing to submit a PR for this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature
